In [2]:
import pandas as pd
import numpy as np

In [9]:
base_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/" # loading from Internet
# base_url = "../../data/COVID/" # loading from disk
infected_dataset_url = base_url + "time_series_covid19_confirmed_global.csv"
recovered_dataset_url = base_url + "time_series_covid19_recovered_global.csv"
deaths_dataset_url = base_url + "time_series_covid19_deaths_global.csv"

In [15]:
df = pd.read_csv(infected_dataset_url)
df.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288

In [17]:
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '2/28/23', '3/1/23', '3/2/23', '3/3/23', '3/4/23', '3/5/23', '3/6/23',
       '3/7/23', '3/8/23', '3/9/23'],
      dtype='object', length=1147)

In [18]:
df.index

RangeIndex(start=0, stop=289, step=1)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Columns: 1147 entries, Province/State to 3/9/23
dtypes: float64(2), int64(1143), object(2)
memory usage: 2.5+ MB

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Lat,287.0,1.971872e+01,2.595661e+01,-71.9499,4.072192,21.512583,4.040178e+01,7.170690e+01
Long,287.0,2.218208e+01,7.787093e+01,-178.1165,-32.823050,20.939400,8.922435e+01,1.780650e+02
1/22/20,289.0,1.927336e+00,2.617366e+01,0.0000,0.000000,0.000000,0.000000e+00,4.440000e+02
1/23/20,289.0,2.273356e+00,2.627019e+01,0.0000,0.000000,0.000000,0.000000e+00,4.440000e+02
1/24/20,289.0,3.266436e+00,3.270727e+01,0.0000,0.000000,0.000000,0.000000e+00,5.490000e+02
...,...,...,...,...,...,...,...,...
3/5/23,289.0,2.339187e+06,8.518645e+06,0.0000,14567.000000,103248.000000,1.052664e+06,1.036470e+08
3/6/23,289.0,2.339387e+06,8.519346e+06,0.0000,14567.000000,103248.000000,1.052664e+06,1.036555e+08
3/7/23,289.0,2.339839e+06,8.521641e+06,0.0000,14567.000000,103248.000000,1.052926e+06,1.036909e+08
3/8/23,289.0,2.340460e+06,8.524968e+06,0.0000,14567.000000,103248.000000,1.053068e+06,1.037558e+08
3/9/23,289.0,2.341073e+06,8.527765e+06,0.0000,14567.000000,103248.000000,1.053213e+06,1.038027e+08

In [21]:
df.shape

(289, 1147)

In [16]:
# Ãœlkelere gÃ¶re grupla ve toplam vaka sayÄ±sÄ±nÄ± al
grouped_by_country = df.groupby('Country/Region').sum()

# GruplandÄ±rÄ±lmÄ±ÅŸ veriyi gÃ¶ster
print(grouped_by_country.head())

                     Lat       Long  1/22/20  1/23/20  1/24/20  1/25/20  \
Country/Region
Afghanistan     33.93911  67.709953        0        0        0        0
Albania         41.15330  20.168300        0        0        0        0
Algeria         28.03390   1.659600        0        0        0        0
Andorra         42.50630   1.521800        0        0        0        0
Angola         -11.20270  17.873900        0        0        0        0

                1/26/20  1/27/20  1/28/20  1/29/20  ...  2/28/23  3/1/23  \
Country/Region                                      ...
Afghanistan           0        0        0        0  ...   209322  209340
Albania               0        0        0        0  ...   334391  334408
Algeria               0        0        0        0  ...   271441  271448
Andorra               0        0        0        0  ...    47866   47875
Angola                0        0        0        0  ...   105255  105277

                3/2/23  3/3/23  3/4/23  3/5/23  3/6/23  3/7/23  3/8/23  3/9/23
Country/Region
Afghanistan     209358  209362  209369  209390  209406  209436  209451  209451
Albania         334408  334427  334427  334427  334427  334427  334443  334457
Algeria         271463  271469  271469  271477  271477  271490  271494  271496
Andorra          47875   47875   47875   47875   47875   47875   47890   47890
Angola          105277  105277  105277  105277  105277  105277  105288  105288

[5 rows x 1145 columns]

<ipython-input-16-fc69ff38891b>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_by_country = df.groupby('Country/Region').sum()